server:
  port: ${SERVER_PORT:8050}
#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/oauth2?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    hikari:
      username: ${DATABASE_USERNAME:root}
      password: ${DATABASE_PASSWORD:root}
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/ddl.sql
      data-locations: classpath:sql/dml.sql
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: ${REDIS_HOST:redis}
      password: ${REDIS_PASSWORD:admin}
      #60s time out
      timeout: 60000
      client-type: jedis
      jedis:
        pool:
          # 最大可用连接数（默认为8，负数表示无限）
          max-active: -1
          # 最大空闲连接数（默认为8，负数表示无限）
          max-idle: 8
          # 最小空闲连接数（默认为0，该值只有为正数才有用）
          min-idle: 0
          # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
          max-wait: -1
    ## 资源服务器
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8050/oauth2-service
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: ${GITHUB_SCOPE:read:user,user:email}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            client-name: ${GITHUB_CLIENT_NAME:GitHub 登录}
oauth2:
  jwkPath: "www.wlngo.top.jks"
  jwkAlias: "www.wlngo.top"
  jwkPass: "www.wlngo.top"
  issuer: "https://wlngo.top:9400"
  domainName: "https://*.api.wlngo.top:[*]"
  login-page-url: "${LOGIN_PAGE_URL:/#/login}"
  consent-page-url: "${CONSENT_PAGE_URL:/#/oauth2/consent}"


