name: 'Deploy-Dev'

on:
  workflow_run:
    workflows: [ "Push-Docker-Hub" ]
    types:
      - completed
jobs:
  deploy-dev:
    runs-on: [ self-hosted,node1 ]
    steps:
      - name: run oauth2
        run: sh /opt/oauth2/update_or_start_container.sh
            
          
