name: 'Deploy-Dev'

on:
  workflow_run:
    workflows: ["Push-Docker-Hub"]

jobs:
  deploy-dev:
    needs: "docker-push"
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "run"
            
          
