name: 'Deploy-Dev'

on:
  workflow_run:
    workflows: [ "Push-Docker-Hub" ]
    types:
      - completed
jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: run oauth2
        run: sh /opt/oauth2-service/update_or_start_container.sh
            
          
